VEDA_OS01/tests/test_transcripts.py, VEDA_OS01/transcripts.py, control/tests/test_deliver_cielo.py, control/veda_deliver_cielo.py
[EDUCATOR-1439](https://openedx.atlassian.net/browse/EDUCATOR-1439)
```bash
perform_transcription(
transcription_fidelity='Professional',
priority='STANDARD ',
callback_url='http://YOURURLHERE/cielo24_calllback?iwp_name={iwp_name}& ...',
options='{"return_iwp":["FINAL"]}'
)
```
=> Add `options` to avoid multiple Cielo24 callbacks.

requirements.txt
**Issue**: ImportError: Could not import `'rest_framework.filters.DjangoFilterBackend'`
DRF-3.7.0 has removed `DjangoFilterBackend`, if we want to move to DRF-3.7.0, we shall be using `'django_filters.rest_framework.DjangoFilterBackend'` instead.
=> Fix drf and django filter versions.

VEDA/tests/test_utils.py, VEDA/utils.py, VEDA_OS01/tests/test_transcripts.py, VEDA_OS01/transcripts.py, control/veda_deliver_3play.py, control/veda_deliver_cielo.py
[EDUCATOR-1631](https://openedx.atlassian.net/browse/EDUCATOR-1631)
This will add `3play` and `cielo24` api urls into logs in case of an error. But before logging, sensitive information will be scrubbed from api url
=> add urls to logs

VEDA_OS01/models.py, bin/loop.py, control/tests/test_file_discovery.py, control/veda_file_discovery.py, static_config.yaml, test_config.yaml
- Course retrieval/creation can be done via `course_id` alone. No hard and fast dependency for `course_hex` except for the courses with youtube dependency.
-  This rewrites File Discovery phase related to Studio along with relevant tests.
=> [File Discovery]  Course can be fetched/created without a course_hex

control/veda_heal.py, control/veda_val.py
Fix encode sending for deprecated encode types. **NOTE:** this fix is live in production.
FYI: @edx/educator-neem
=> Change HEAL for legacy video encodes.

bin/heal, control/veda_heal.py
Added 'no_audio' optional flag to HEAL command, to skip over mp3 encoding if a video has no audio.
=> Add 'no_audio' optional flag to HEAL command

VEDA/urls.py, VEDA_OS01/utils.py, VEDA_OS01/views.py, control/veda_file_discovery.py
HTTP endpoint to handle ingest notifications from s3, called by an SNS.
Permissions should probably be done [this way](https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.verify.signature.html?shortFooter=true)
=> EDUCATOR 2938 Create HTTP video ingest API

VEDA_OS01/management/commands/re_send_sns_notification.py
Re-send SNS notifications for either:
- a valid s3 key (a studio upload ID)
- a date (where all videos modified before that date will be processed)
=> Management command to re-send SNS notifications

VEDA/settings/base.py
We should always reference the root_path using absolute path.
=> Use abspath to specify the template path

control/tests/test_deliver_3play.py, control/veda_deliver_3play.py
3plyaMedia have updated their API. This has caused the failure of existing 3Play integrations in edx video pipeline. In this PR we are specifying a folder to keep files in it, as per new update in 3Play, following behavior is expected
> Alternatively, you can upload to a specific folder with the batch_name attribute. If a folder with that name already exists, the file will go there. If it does not exist, it will be created for you.
>If a folder is not specified, or the specified folder is not found, the upload will go into your last created folder. If you have no folders on file, the file will go into a new folder named "API Upload Folder".
=> add default directory for uploads to 3play

control/veda_file_ingest.py
@yro Please review
We had another about video ingest breakage, because the video name to be ingested was
`MOOC_Promo_004_Valoración_Financiera_Comprimido (1).m4v`. Note the bracket in the name. That introduced problems with ffprobe
=> Fix the about video ingest with names containing brackets

requirements.txt
This fix is made according to the conversation at https://github.com/celery/celery/issues/5369
Without this fix, we would encounter the following error on app start:
```
VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
```
=> Fix the kombu dependency that broke the redis

VEDA_OS01/views.py, control/http_ingest_celeryapp.py, http_ingest_worker.sh, instance_config.yaml
PROD-411: Move ingest and upload to hotstore of course videos to celery task.  Prevents api call from AWS from timing out and retrying, which results in extra encode requests.
=> PROD-411: Move ingest processing to celery task.  

VEDA_OS01/management/commands/re_encode_videos_missing_hls.py
This corrects the path to the encode_tasks module.  Required for the re_encode_videos_missing_hls management command.
=> PROD-506: Fix import so that hls encode management command will run.

requirements.txt
We were getting a security alert due to a very old version of gunicorn that we had listed in our requirements.txt file, but it turns out that we are not using this package, and it is not a dependency of anything that we are using.
=> Remove unneeded dependency on gunicorn package.

VEDA/settings/base.py, VEDA/settings/local.py, VEDA/settings/production.py, VEDA/settings/stage.py, VEDA_OS01/tests/test_transcripts.py, control/tests/test_deliver.py, control/tests/test_heal.py, control/tests/test_val.py, control/veda_val.py, instance_config.yaml, requirements.txt, test_config.yaml
Changes the authentication method used within edx-video-pipeline to use Django Oauth Toolkit (DOT) for authentication, due to the previous method (DOP) being deprecated.
=> PROD-549: Use Django Oauth Toolkit for authentication.

control/veda_val.py
Due to a bug in a previous commit I was calling the wrong URL for updating video status.
=> Fix 405 errors when uploading status for about videos.

VEDA_OS01/models.py
This change fixes the display of object names in the django admin tool.  For example, we see things like "course object" instead of the actual course name.  This was broken when we upgraded to python 3.
=> PROD-865:  Change __unicode__ to __str__ for django models.

frontend/views.py
About video uploads are currently failing during the S3 upload due to "SignatureDoesNotMatch" errors.  I think this may be because of b64encode returning bytes under python3, instead of strings which were returned previously.  This changes the bytes back to strings.
=> PROD-1373: Fix encoding issues for about page upload form.

frontend/abvid_validate.py, frontend/views.py
Add validation for the `success` field in the upload data used for about video uploads.  Fixes exception caused by lowercase "true" being passed in and Django allowing only "True" or "False".
=> PROD-1386: Fix exception during about video upload.

VEDA/settings/base.py, VEDA/settings/production.py
By defining a key in `DICT_UPDATE_KEYS`, the existing values are not overridden but updated with the values in the config file. JWT_AUTH is not among the values. This PR adds JWT_AUTH to that list and adds the set of default JWT_AUTH values that are missing in VEDA
=> add JWT_AUTH dict update at production
