edx/edx-video-pipeline

- control/veda_val.py
Bug fix for op failure 7.10.2017
> Update val url handling

- control/veda_val.py
Fix image handling/dict comparison for VAL 200
All code credit goes to @Qubad786
> Fir Integrity Errors

- .coveragerc
- .gitignore
- .pep8
- .travis.yml
- Makefile
- VEDA/django_secrets.py
- VEDA/urls.py
- VEDA_OS01/admin.py
- VEDA_OS01/api.py
- VEDA_OS01/models.py
- VEDA_OS01/views.py
- codecov.yml
- control/celeryapp.py
- control/tests/test_encode.py
- control/tests/test_file_discovery.py
- control/tests/test_heal.py
- control/tests/test_hotstore.py
- control/tests/test_video_validation.py
- frontend/tests/test_abvid_reporting.py
- reports/test
- test_requirements.txt
General cleanup to test out Travis integration.
> Travis and Codecov integration.

- control/veda_file_ingest.py
- control/veda_val.py
Update Ingest URL handling for API calls
> Update URL handling

- youtube_callback/sftp_id_retrieve.py
> csv fnmatch fix

- VEDA_OS01/admin.py
- VEDA_OS01/models.py
The purpose of this PR is to save save transcription process metadata and show in admin side.
> Save transcription process metadata

- VEDA_OS01/serializers.py
> Make course ids available to auto-generated images.

- .gitignore
- VEDA_OS01/admin.py
- VEDA_OS01/models.py
- VEDA_OS01/serializers.py
- control/veda_file_discovery.py
- control/veda_file_ingest.py
1. Add transcript preferences in Video
2. Expect the transcript preferences in file discovery phase
3. Pass these preferences from file discovery to ingestion phase for cataloging
@muzaffaryousaf
> Add transcript preferences in Video

- bin/deliver
- control/veda_deliver.py
- control/veda_encode.py
- control/veda_file_discovery.py
- control/veda_file_ingest.py
- control/veda_heal.py
- control/veda_hotstore.py
- control/veda_utils.py
- control/veda_val.py
- control/veda_video_validation.py
- youtube_callback/daemon.py
- youtube_callback/sftp_id_retrieve.py
Will use function wrappers for prod instead of decorators, eliminating need for provisioning newrelic.ini files
> Eliminate NR decorators

- .coveragerc
- .gitignore
- .travis.yml
- AUTHORS
- Makefile
- VEDA/test_settings.py
- VEDA_OS01/tests/test_transcripts.py
- control/tests/test_deliver_cielo.py
- control/tests/test_encode.py
- control/tests/test_file_discovery.py
- control/tests/test_file_ingest.py
- control/tests/test_heal.py
- control/tests/test_hotstore.py
- control/tests/test_reporting.py
- control/tests/test_val.py
- control/tests/test_video_validation.py
- control/veda_deliver.py
- frontend/tests/test_abvid_reporting.py
- frontend/tests/test_cat_tool.py
- instance_config.yaml
- pytest.ini
- test_config.yaml
- test_requirements.txt
@muzaffaryousaf @yro These changes will make the build green. Please have a look.
> green build

- VEDA_OS01/tests/test_transcripts.py
- VEDA_OS01/transcripts.py
- control/tests/test_deliver_cielo.py
- control/veda_deliver_cielo.py
- control/veda_val.py
@Qubad786 Can you review the changes. These changes are required to make cielo24 integration work as expected.
> cielo24 fixes

- VEDA_OS01/transcripts.py
- control/tests/test_deliver_3play.py
- control/tests/test_deliver_cielo.py
- control/veda_deliver.py
- control/veda_deliver_3play.py
- control/veda_deliver_cielo.py
- instance_config.yaml
- test_config.yaml
[EDUCATOR-1278](https://openedx.atlassian.net/browse/EDUCATOR-1278)
> replace 3rdparty transcript urls

- VEDA_OS01/admin.py
- VEDA_OS01/models.py
- youtube_callback/daemon.py
- youtube_callback/sftp_id_retrieve.py
Change YT callback window, update Admin settings
> Update Admin Settings

- control/tests/test_heal.py
- control/veda_heal.py
- requirements.txt
Unskip and fix HEAL unittests.
> Green HEAL tests

- control/veda_val.py
- instance_config.yaml
Set and update global timeout (causing node failure more increasingly)
> Implement global timeout

- Makefile
- VEDA/django_secrets.py
- VEDA/settings.py
- instance_config.yaml
- requirements.txt
@yro @muzaffaryousaf @mushtaqak @Qubad786 These are the changes required to make ansible role working. Please review the changes.
> changes for config role

- VEDA/settings/base.py
- VEDA/settings/local.py
- VEDA/settings/production.py
- instance_config.yaml
- requirements.txt
[EDUCATOR-1335](https://openedx.atlassian.net/browse/EDUCATOR-1335)
[Related platform PR](https://github.com/edx/edx-platform/pull/16116)
> Add JWT settings

- VEDA/urls.py
- VEDA_OS01/tests/test_transcripts.py
- VEDA_OS01/tests/test_views.py
- VEDA_OS01/transcripts.py
- VEDA_OS01/views.py
- control/tests/test_deliver_cielo.py
- control/veda_deliver_cielo.py
[EDUCATOR-1335](https://openedx.atlassian.net/browse/EDUCATOR-1335)
[Related platform PR](https://github.com/edx/edx-platform/pull/16116)
> Save transcript credentials backend view

- .coveragerc
- VEDA_OS01/management/commands/create_oauth_client.py
- VEDA_OS01/management/commands/tests/test_create_oauth_client.py
This add a management command to create oauth application client.
> add management command to create oauth client

- .coveragerc
- .pep8
- Makefile
- pavelib/quality.py
- pavelib/tests/pavelib_test_code/test_pylint.py
- pavelib/tests/pylint_test_list.json
- pavelib/tests/test_quality.py
- pylintrc
- pytest.ini
[EDUCATOR-1620](https://openedx.atlassian.net/browse/EDUCATOR-1620)
This adds tests for paver quality tasks.
> add tests for paver tasks

- VEDA/urls.py
- VEDA_OS01/tests/test_views.py
- VEDA_OS01/views.py
[EDUCATOR-1632](https://openedx.atlassian.net/browse/EDUCATOR-1632)
> heartbeat endpoint

- Makefile
- VEDA_OS01/management/commands/re_encrypt_transcript_credentials.py
- VEDA_OS01/management/commands/tests/test_re_encrypt_transcript_credentials.py
- VEDA_OS01/tests/test_models.py
- VEDA_OS01/tests/test_utils.py
- VEDA_OS01/utils.py
- instance_config.yaml
This PR adds a management command to re-encrypt transcript credentials.
[EDUCATOR-1490](https://openedx.atlassian.net/browse/EDUCATOR-1490)
> Re-encrypt transcript credentials

- VEDA/tests/test_utils.py
- VEDA/utils.py
- instance_config.yaml
- static_config.yaml
This will move the static configuration into its own yaml file. We need this to avoid updating ansible role every time we introduce a new variable. From now onwards please add all static configuration in `static_config.yaml`
> separate static configuration

- bin/deliver
- bin/heal
- control/veda_deliver.py
- control/veda_heal.py
- instance_config.yaml
- static_config.yaml
Change heal queue, make logging for deliver/heal louder
> Refine HEAL process, make logging louder

- bin/heal
- control/tests/test_heal.py
- control/veda_file_discovery.py
- control/veda_file_ingest.py
- control/veda_heal.py
- youtube_callback/sftp_id_retrieve.py
Change heal queue and encode worker queue.
> 1.2.0 Release Debug

- VEDA_OS01/admin.py
- VEDA_OS01/models.py
This is to improve transcript process metadata admin.
[EDUCATOR-1942](https://openedx.atlassian.net/browse/EDUCATOR-1942)
> Improve process metadata admin

- VEDA/settings/utils.py
- control/veda_val.py
> Fix logging issues on production.

- VEDA_OS01/admin.py
- VEDA_OS01/models.py
- control/veda_file_discovery.py
- static_config.yaml
- youtube_callback/sftp_id_retrieve.py
Deployment bug fix - Dec. 6th, 2017
Release 1.2.1, 1.2.1b
> Deployment Bugfix

- VEDA_OS01/transcripts.py
- bin/heal
[EDUCATOR-1979](https://openedx.atlassian.net/browse/EDUCATOR-1979)
Improve logging and add an option to run 3play translations with heal.
> Improve logging and add an option to run 3play translations.

- VEDA/settings/production.py
- VEDA/tests/test_utils.py
- VEDA/utils.py
- VEDA_OS01/fixtures/encodes.json
- VEDA_OS01/models.py
- VEDA_OS01/tests/test_transcripts.py
- VEDA_OS01/transcripts.py
- bin/loop.py
- control/control_env.py
- control/veda_deliver.py
- control/veda_file_discovery.py
- frontend/views.py
- instance_config.yaml
- templates/upload_video.html
- test_config.yaml
Fixes required for veda sandbox built using Ansible.
@yro @Qubad786 Please review these changes.
> sandbox testing fixes

- VEDA_OS01/tests/factories.py
- VEDA_OS01/tests/test_utils.py
- VEDA_OS01/utils.py
- control/tests/test_deliver.py
- control/veda_deliver.py
- test_requirements.txt
[EDUCATOR-2033](https://openedx.atlassian.net/browse/EDUCATOR-2033)
Start transcription when a video encodings are ready (except for "review" and "youtube" encodes).
> Start transcription once video encodings(except for "review" and "youtube") get ready

- VEDA/settings/production.py
- VEDA/tests/test_utils.py
- VEDA/utils.py
- VEDA_OS01/fixtures/encodes.json
- VEDA_OS01/models.py
- VEDA_OS01/tests/test_transcripts.py
- VEDA_OS01/transcripts.py
- bin/loop.py
- control/control_env.py
- control/veda_deliver.py
- control/veda_file_discovery.py
- frontend/views.py
- instance_config.yaml
- templates/upload_video.html
- test_config.yaml
This PR is the revert of https://github.com/edx/edx-video-pipeline/pull/86
> sandbox fixes

- control/old_veda_deliver_cielo.py
- control/veda_deliver.py
- static_config.yaml
[EDUCATOR-2408](https://openedx.atlassian.net/browse/EDUCATOR-2408)
This restores old transcription flow when credentials were stored with VEDA course.
> Restore old transcription workflow

- control/veda_file_ingest.py
Fix indexing issue preventing sandbox builds.
Currently running on https://yro.sandbox.edx.org
> Remove Indexing

- control/veda_deliver.py
[EDUCATOR-2517](https://openedx.atlassian.net/browse/EDUCATOR-2517)
> fix platform url assignment

- control/veda_heal.py
Fix HEAL status updater.
FYI: @edx/educator-neem
> VEDA Release Mar 29, 2018

- control/tests/test_val.py
- control/veda_val.py
[EDUCATOR-2609](https://openedx.atlassian.net/browse/EDUCATOR-2609)
[Sandbox](ma-pipeline-c24-fix.sandbox.edx.org)
> fix status update

- docker/Makefile
- docker/README.md
- docker/docker-compose.yml
- instance_config.yaml
This directory is the current state of the work to docker-ize VEDA so it can be run locally. 
More info in the README.
> MakeFile and docker compose file to run VEDA locally. 

- instance_config.yaml
- static_config.yaml
[EDUCATOR-2716](https://openedx.atlassian.net/browse/EDUCATOR-2716)
> Fix Cielo24 transcripts still in progress

- youtube_callback/sftp_id_retrieve.py
Videos with a required youtube upload are uploading to youtube but never "completing" in VEDA.
> Multiple courses stuck in YouTube renditions

- control/veda_val.py
More logging, just in case we run into the duplicate video ID problem again.
> Adding logging for ingest process

- control/veda_file_ingest.py
This updates the logging for corrupt files, which was causing a crash at this line for the ingest daemon.
@schenedx please thumb and I will release.
> Update logging for corrupt files

- config/ingest.conf
- config/youtubecallback.conf
The two new conf files are init daemons for ingest and youtube_callback processes.
Please review
@yro and @ssemenova 
I tested the conf file on production pipeline worker
> create the init daemon configurations

- VEDA_OS01/management/commands/re_ingest_from_hotstore.py
> Add the management command of re-ingest_from_hotstore

- control/veda_file_ingest.py
Fixing ingest race condition, where two videos get saved under the same video number.
> Fixing ingest race condition

- bin/loop.py
- control/veda_file_discovery.py
Putting back about video ingest.
> About video ingest 

- control/veda_file_discovery.py
- control/veda_file_ingest.py
This will fix the about video ingest process when a video filename is like
```
Laudato Si' - Trailer [720p].mp4
```
> Update the about video ingest to handle complicated file names

- VEDA_OS01/management/commands/re_send_sns_notification.py
This is a simple bug fix on the management command
> Fix the management command to resend SNS

- control/veda_file_ingest.py
@yro Please review.
With this change, we can handle about video names like 
`Fisica II _ Vincenzo Canale & Francesco Bloisi _ Trailer.mp4`
> Fix about page ingest name problem

- control/veda_file_ingest.py
[EDUCATOR-3550](https://openedx.atlassian.net/browse/EDUCATOR-3550)
@yro If you are still here, please review.
> Add another special character handling to veda ingest

- AUTHORS
- VEDA/settings/base.py
- requirements.txt
> ARCH-255: Update edx-drf-extensions imports.

- VEDA_OS01/management/commands/re_encode_videos_missing_hls.py
Incorporated changes introduced in: https://github.com/edx/edx-val/pull/167
> Refactor expedited re-encode endpoints

- bin/heal
Update course heal command to take on institution ID as well in order to handle a wider range of courses in our video pipeline
> Fix course heal

- templates/heal.html
Added some simple bootstrap styling to heal page.  Attaching screenshots illustrating the state before and after.
Before:
After:
> Use bootstrap for heal page.

- VEDA/urls.py
- bin/deliver
- control/celeryapp.py
- control/veda_heal.py
- frontend/urls.py
- frontend/views.py
- instance_config.yaml
- test_config.yaml
This reverts commit d1bf76eaea200e4a1405975620fc15a77503c033.
> Revert "Azarembok/veda heal (#155)"

- VEDA/urls.py
- VEDA_OS01/management/commands/re_encode_videos_missing_hls.py
- bin/deliver
- control/celeryapp.py
- control/encode_worker_tasks.py
- control/veda_heal.py
- frontend/urls.py
- frontend/views.py
- instance_config.yaml
- test_config.yaml
Restore code for heal tool that was previously reverted, and correct method of calling remote celery task in encode worker.
> PROD-373:  Restore web heal function, refactor invocation of remote celery tasks.

- config/ingest.service
- config/veda_syslog.conf
- config/youtubecallback.service
Fix logging for our systemd services to send output to our own logs directory.
> EDUCATOR-4101: Fix logging for our systemd services

- config/ingest.service
- config/veda_syslog.conf
- config/youtubecallback.service
Change names of logfiles for our systemd services to match what our splunk configuration expects,
and set permissions to make files readable.
> EDUCATOR-4101: Change names of logfiles for systemd services. 

- frontend/views.py
Needed for update to django 1.11.
> PROD-469: Update calls to template.render to pass context correctly.

- VEDA_OS01/management/commands/re_encode_videos_missing_hls.py
- control/encode_worker_tasks.py
- control/veda_heal.py
Ensure that encode requests go to the correct queue for processing.
HLS re-encode requests go to low priority queue, normal encode/heal requests
go to medium priority queue.
> PROD-506:  Send encode requests to correct queue.

- frontend/views.py
- templates/heal.html
Also fixes PROD-414:  Changed text on VEDA heal page to indicate that VEDA id is required.
> PROD-509:  Fix 500 error after submitting heal request.

- openedx.yaml
> Mark OEP-7 flag true.

- .travis.yml
- VEDA/settings/base.py
- VEDA_OS01/views.py
- requirements.txt
- tox.ini
Reverts edx/edx-video-pipeline#195
> Revert "PROD-850: Update version of djangorestframework."

- .travis.yml
- VEDA/settings/base.py
- VEDA_OS01/views.py
- requirements.txt
- tox.ini
Reverts edx/edx-video-pipeline#196
> Revert "Revert "PROD-850: Update version of djangorestframework.""

- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Reverts edx/edx-video-pipeline#202
> Revert "PROD-1169: Update dependencies for deployment with django 2.2."

- control/veda_val.py
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Correct use of nested querysets to fix ValueError exception.
> Update requirements for deployment with Django2.2.

- VEDA_OS01/views.py
- frontend/views.py
- requirements/base.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Logins to veda.edx.org have been experiencing either hangs or 500 errors depending on the exact URL used.  This is due to a change in django2 that made user.is_authenticated an attribute rather than a function.  This PR changes our code accordingly.
> PROD-1391: fix use of is_authenticated to cleanup login errors

- control/veda_val.py
- requirements/base.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Use infinitely long timeout with OAuthApiClient to prevent ingest and other failures due to ReadTimeout exceptions.
> PROD-1411: Video ingest failures due to read timeout.

- .travis.yml
- requirements/base.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- tox.ini
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1603)
> Added support for python 3.8 and dropped support for older Django versions

- requirements/base.txt
- requirements/constraints.txt
- requirements/pip-tools.txt
- requirements/quality.in
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
- tox.ini
https://openedx.atlassian.net/browse/BOM-1651
> BOM-1651 : Remove caniusepython3

- requirements/base.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Reverts edx/edx-video-pipeline#222
> Revert "Update requirements."

- requirements/base.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/travis.txt
Upgrade drf-jwt to latest version
> Upgrade drf-jwt to latest version
